version: '3.8'
services:   
  db:
    image: mysql:5.6
    container_name: educaredb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: educare_prod
      MYSQL_USER: educare
      MYSQL_PASSWORD: EducareHitpL_2019
    ports:
      - "3309:3306"
    networks:
      - tomcat-network-educare
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

      
  tomcat:
    build:
      context: .
    image: educareimage
    container_name: educareapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: deducare_prod
      MYSQL_USER: educare
      MYSQL_PASSWORD: ducareHitpL_2019
    ports:
      - "8099:8080"
    networks:
      - tomcat-network-educare

  
networks:
  tomcat-network-educare:  # Custom network for communication between Tomcat and MySQL
    driver: bridge


 
