services:
  db:
    image: mysql:5.6
    container_name: educaredb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: educare_prod
      MYSQL_USER: educare
      MYSQL_PASSWORD: EducareHitpL_2019
    ports:
      - "3306:3306"
    volumes:
     - ./db_educare_prod.sql:/docker-entrypoint-initdb.d/db_educare_prod.sql
     - ./mysql/data:/var/lib/mysql
     - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - tomcat-network-educare
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pmysql123 -e 'SELECT 1'"]
      interval: 10s
      retries: 10
      start_period: 40s


  tomcat:
    build:
      context: .
    image: jaicswamy962/educareimage:latest
    container_name: educareapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: educare_prod
      MYSQL_USER: educare
      MYSQL_PASSWORD: EducareHitpL_2019
    ports:
      - "8081:8080"
    networks:
      - tomcat-network-educare


networks:
  tomcat-network-educare:  
    driver: bridge
